language: java

services:
  - docker

#this means it will only build on master branch
branches:
  only:
    - master

before_install:
  - docker build -t app .
  - docker image ls

script:
  docker run app

after_success:
  - echo "TRAVIS BRANCH ${TRAVIS_BRANCH}"
  - ./deploy.sh
